''' Fields for BHA reports '''

## Any not listed here are strings
REPORTING_FIELD_TYPES = {
  # dimension
  'AdvancedBookingWindow': 'integer',
  'CheckinDay': 'integer',
  'Date': 'date',
  'DateType': 'string',
  'DeviceType': 'string',
  'HotelCountry': 'string',
  'HotelGroupId': 'string',
  'HotelGroupName': 'string',
  'HotelId': 'string',
  'HotelName': 'string',
  'LengthOfStay': 'integer',
  'PartnerHotelId': 'string',
  'SiteType': 'string',
  'SlotType': 'string',
  'SubAccountId': 'string',
  'SubAccountName': 'string',
  'UserCountry': 'string',
  # measure
  'AverageCPC': 'number',
  'AverageCPCUSD': 'number',
  'AveragePosition': 'number',
  'AverageSlotPosition': 'number',
  'AvgBookedABW': 'number',
  'AvgBookedNights': 'number',
  'BookedABW': 'integer',
  'Clicks': 'integer',
  'ClickShare': 'number',
  'Conversions': 'integer',
  'ConversionRate': 'number',
  'CPA': 'number',
  'CTR': 'number',
  'EligibleImpressions': 'integer',
  'Impressions': 'integer',
  'GrossRevenue': 'number',
  'GrossRevenuePerClick': 'number',
  'GrossRevenuePerConv': 'number',
  'GrossROAS': 'number',
  'ImpressionShare': 'number',
  'MissedImpressions': 'integer',
  'MissedImpressionsInsufficientBid': 'integer',
  'MissedImpressionsNoTax': 'integer',
  'MissedImpressionsOther': 'integer',
  'MissedImpressionsSpendingCapReached': 'integer',
  'NetRevenue': 'number',
  'NetROAS': 'number',
  'Spend': 'number',
  'SpendUSD': 'number',
  'TotalBookedNights': 'integer',
}

REPORTING_FIELDNAME_MAP = {
  # dimensions
  'Adv. booking window': 'AdvancedBookingWindow',
  'Checkin day': 'CheckinDay',
  'Date': 'Date',
  'Date type': 'DateType',
  'Device type': 'DeviceType',
  'Hotel country': 'HotelCountry',
  'Hotel group ID': 'HotelGroupId',
  'Hotel group name': 'HotelGroupName',
  'Hotel ID': 'HotelId',
  'Hotel name': 'HotelName',
  'Length of stay': 'LengthOfStay',
  'Partner hotel ID': 'PartnerHotelId',
  'Site type': 'SiteType',
  'Slot type': 'SlotType',
  'Subaccount ID': 'SubAccountId',
  'User country': 'UserCountry',
  # measure
  'Avg. CPC': 'AverageCPC',
  'Avg. CPC USD': 'AverageCPCUSD',
  'Avg. pos.': 'AveragePosition',
  'Avg. slot. pos.': 'AveragePosition',
  'Avg booked ABW': 'AvgBookedABW',
  'Avg booked nights': 'AvgBookedNights',
  'Booked ABW': 'BookedABW',
  'Booked length of stay': 'TotalBookedNights',
  'Clicks': 'Clicks',
  'Click share': 'ClickShare',
  'Conversions': 'Conversions',
  'Conversion rate': 'ConversionRate',
  'CPA': 'CPA',
  'CTR': 'CTR',
  'Eligible impr.': 'EligibleImpressions',
  'Impr.': 'Impressions',
  'Gross revenue': 'GrossRevenue',
  'Gross revenue / click': 'GrossRevenuePerClick',
  'Gross revenue / conv': 'GrossRevenuePerConv',
  'Gross ROAS': 'GrossROAS',
  'Impr. share': 'ImpressionShare',
  'Missed impr.': 'MissedImpressions',
  'Missed impr. insufficient bid': 'MissedImpressionsInsufficientBid',
  'Missed impr. other': 'MissedImpressionsOther',
  'Missed impr. spending cap reached': 'MissedImpressionsSpendingCapReached',
  'Net revenue': 'NetRevenue',
  'Net revenue / click': 'NetRevenuePerClick',
  'Net revenue / conv': 'NetRevenueConv',
  'Net ROAS': 'NetROAS',
  'Spend': 'Spend',
  'Spend USD': 'SpendUSD',
}
